new_dawn_server/questions/admin.py
new_dawn_server/users/admin.py

- Registered superuser on local and tested admin page after runserver. #37 
- Changed spacing in admin files.

Registered question models to admin

---

.ebextensions/db-migrate.config
new_dawn_server/management/commands/create_super_user.py

A command to create super user in prod
Test: Be able to login in using the real credential in http://django-env.w8iffghn9z.us-west-2.elasticbeanstalk.com/admin/

Create a command to create super user in prod

---

README.md
new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_users_api.py

The response data is the newly created obj's serialized json
Unit test is added

Let registration POST request to return response obj data

---

new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_users_api.py

Add test to verify that login can be successful.
Will change authentication/authorization level for private models such as account, profile, etc.

Add username/password login API. Response with Access Token

---

new_dawn_server/urls.py
new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_users_api.py

#50 
Sample return:
{"meta": {"limit": 20, "next": null, "offset": 0, "previous": null, "total_count": 1}, "objects": [{"account": {"birthday": "1800-01-01", "creation_date": "2018-12-05", "gender": "M", "id": 6, "name": "ziyi_tang", "phone_number": "+11111111111", "resource_uri": "/api/v1/account/6/", "user": {"date_joined": "2018-12-05T22:32:08.557158", "email": "", "first_name": "ziyi", "id": 7, "is_active": true, "is_superuser": false, "last_login": null, "last_name": "tang", "resource_uri": "/api/v1/user/7/", "username": "goodman"}}, "city_preference": null, "description": null, "employer": null, "height": null, "hometown": null, "id": 6, "job_title": null, "profile_photo_url": null, "resource_uri": "/api/v1/profile/6/", "school": null, "smoke": null, "update_time": …

Get API for profile

---

new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_users_api.py

So front end can directly specify the username in url to query the profile for a specific user
Add unit test

Add user-based filtering in profile resource.

---

new_dawn_server/locations/api/resources.py
new_dawn_server/locations/api/tests/test_city_preference_api.py
new_dawn_server/urls.py
new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_account_city_fields.py
new_dawn_server/users/api/tests/test_account_city_preference.py
new_dawn_server/users/api/tests/test_users_api.py

#38 
Account Post, "User, Account, City" models can be co-created.

Location Resouce, and Location co-created in Account API

---

new_dawn_server/questions/api/resources.py
new_dawn_server/questions/api/tests/test_questions_api.py

#74 
Make it available for front-end to retrieve admin defined questions with sample answer

Added filter for question non-user-defined question

---

new_dawn_server/locations/api/resources.py
new_dawn_server/questions/api/resources.py
new_dawn_server/questions/api/tests/test_questions_api.py
new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_account_city_preference.py
new_dawn_server/users/api/tests/test_authentication.py
new_dawn_server/users/api/tests/test_users_api.py

#82 
MultiAuthentication works when any of its authentication method is fulfilled

Added basic + api authentication except medias

---

new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_authentication.py

Temporarily disable authentication for profile

---

new_dawn_server/actions/admin.py
new_dawn_server/actions/api/resources.py
new_dawn_server/actions/api/tests/test_like.py

#88 
- User action admin
- Hydrate user account fields

Action API preparation

---

new_dawn_server/medias/models.py
new_dawn_server/medias/tests/test_image_request.py
new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_users_api.py

- Media tests with SimpleUploadedFile that exists as an inMemoryFile.

Image test with SimpleUploadedfile

---

new_dawn_server/actions/api/resources.py
new_dawn_server/actions/api/tests/test_message.py
new_dawn_server/pusher/chat_service.py

Given a pair of user, the API can respond with all historical messages sent between the two sorted by update time.

[Chat] Two-side chat message API

---

.ebextensions/db-migrate.config
new_dawn_server/actions/api/resources.py
new_dawn_server/actions/api/tests/test_message.py
new_dawn_server/actions/constants.py
new_dawn_server/management/commands/create_test_actions.py
new_dawn_server/management/commands/create_test_users.py
runserver.sh

Fetch all messages from whom the current user is matched with. This API will be used when the root Chat page is loaded. The messages are then stored locally so we can deprecate individual message GET API.

[Chat] Bulk API to read messages from all matched users

---

new_dawn_server/actions/api/resources.py
new_dawn_server/actions/constants.py

The image url is used for Chat page to display user profile photo

Include image url in message API

---

new_dawn_server/management/commands/create_test_actions.py
new_dawn_server/users/api/resources.py

Create Test QA in server db

---

new_dawn_server/actions/api/resources.py

This is for front-end to keep track of latest read message

[Easy] Return message_id from chat page

---

new_dawn_server/users/api/resources.py

[Like] Catch exception if cannot get the liked item (due to deletion, etc.)

---

new_dawn_server/users/api/resources.py

Previously, it only returns user id

[login] Return username and token after login

---

new_dawn_server/medias/api/resources.py
new_dawn_server/medias/tests/test_image_request.py

When images return from query-set, order by user id and order.

Images ordering

---

new_dawn_server/management/commands/create_test_actions.py
new_dawn_server/settings.py
new_dawn_server/users/api/resources.py
requirements.txt

Get rid of testing database which got removed every time during refreshing

[RDS] Setup RDS database as persistent storage

---

new_dawn_server/actions/api/resources.py
new_dawn_server/pusher/notification_service.py

This is to make sure we'll not return 500 when exception happens during notification

[easy] Add try...except around notification exception

---

new_dawn_server/actions/api/tests/test_like.py
new_dawn_server/users/api/resources.py

This is to make sure we can fetch what I liked you when opening the chat page

[Like] Return like info from me to you

---

new_dawn_server/actions/api/tests/test_like.py
new_dawn_server/users/api/resources.py

[easy] Like me return info fix

---

new_dawn_server/actions/api/resources.py
new_dawn_server/actions/api/tests/test_like.py
new_dawn_server/actions/constants.py

Will remove all likes, matches, messages and relationship between two users if any one of them send unmatch request between them.
Add unit test

[Unmatch] Unmatch API

---

new_dawn_server/users/api/resources.py
new_dawn_server/users/api/tests/test_users_api.py

Implemented the filter and ran unit tests

Implemented height and age filter in user preference

---

new_dawn_server/users/admin.py

[review tool] Allow delete users

---

new_dawn_server/actions/models.py
new_dawn_server/medias/models.py

[easy] Add __str__ to some models so we can identify them in admin

---

new_dawn_server/users/api/resources.py

We want to have a special flag to skip phone verification.
This should only be used by internal people who want to test functionalities or do automatic tests.

[Skip] Add skip flag to phone verification for tests

---

new_dawn_server/actions/api/resources.py
new_dawn_server/actions/api/tests/test_message.py
new_dawn_server/actions/constants.py

Make sure the latest message or match will appear on the top of the chat page
Test with a simulation match/message test case

[Chat] Sort chat messages/match according to last update time

---

new_dawn_server/actions/api/resources.py
new_dawn_server/actions/api/tests/test_message.py

- Notification when receive messages
- patch in unit test

[Notification] Notify recipient messages

---

new_dawn_server/settings.py
new_dawn_server/users/api/resources.py

We can change this param via app config and deploy this instantly to all hosts
Test with local host:

Configurable num of profiles recommended
